import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import React from "react";
import AuthGuard from "../components/AuthGuard";
import Header from "../components/Header";
import { AppSidebar } from "../components/sidebar/Sidebar";
import { Toaster } from 'sonner'
import "./globals.css";
import { TooltipProvider } from "../components/ui/tooltip";
import {
  SidebarInset,
  SidebarProvider,
} from "../components/ui/sidebar"

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Form-Builder",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased`}
            >
                <SidebarProvider
                    style={
                        {
                            "--sidebar-width": "calc(var(--spacing) * 72)",
                            "--header-height": "calc(var(--spacing) * 12)",
                        } as React.CSSProperties
                    }
                >
                    <AppSidebar variant="inset" />
                    <SidebarInset>
                        <Header />
                        <Toaster position="top-right" />
                        <AuthGuard>
                            <TooltipProvider>{children}</TooltipProvider>
                        </AuthGuard>
                    </SidebarInset>
                </SidebarProvider>
            </body>
        </html>
    );
}
