import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import React from "react";
import AuthGuard from "../components/AuthGuard";
import Header from "../components/Header";
import ToasterWrapper from "../components/ToasterWrapper";
import "./globals.css";
import { TooltipProvider } from "../components/ui/tooltip";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Form-Builder",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased`}
            >
                <Header />
                <ToasterWrapper />
                <AuthGuard>
                    <TooltipProvider>{children}</TooltipProvider>
                </AuthGuard>
            </body>
        </html>
    );
}
