# Generated by Django 5.2.7 on 2025-10-02 11:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmissionRateLimit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ip_address', models.GenericIPAddressField()),
                ('submission_count', models.PositiveIntegerField(default=1)),
                ('first_submission_at', models.DateTimeField(auto_now_add=True)),
                ('last_submission_at', models.DateTimeField(auto_now=True)),
                ('is_blocked', models.BooleanField(default=False)),
                ('blocked_until', models.DateTimeField(blank=True, null=True)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate_limits', to='forms.form')),
            ],
            options={
                'indexes': [models.Index(fields=['form', 'ip_address', 'last_submission_at'], name='ratelimit_s_form_id_85df69_idx')],
                'unique_together': {('form', 'ip_address')},
            },
        ),
    ]
