# Generated by Django 5.2.7 on 2025-10-02 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratelimit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissionratelimit',
            name='submission_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
