# Generated by Django 5.2.7 on 2025-10-02 11:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_template', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('allow_multiple_submissions', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(unique=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_password_protected', models.BooleanField(default=False)),
                ('access_code', models.CharField(blank=True, max_length=255, null=True)),
                ('enable_email_notifications', models.BooleanField(default=False)),
                ('notification_emails', models.JSONField(blank=True, default=list)),
                ('rate_limit_enabled', models.BooleanField(default=True)),
                ('rate_limit_count', models.PositiveIntegerField(default=5)),
                ('rate_limit_period', models.PositiveIntegerField(default=3600)),
                ('allow_partial_saves', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question_text', models.TextField()),
                ('question_type', models.CharField(choices=[('text', 'Text'), ('email', 'Email'), ('number', 'Number'), ('date', 'Date'), ('textarea', 'Textarea'), ('radio', 'Radio'), ('checkbox', 'Checkbox'), ('dropdown', 'Dropdown')], max_length=50)),
                ('is_required', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField()),
                ('placeholder', models.CharField(blank=True, max_length=255, null=True)),
                ('min_length', models.PositiveIntegerField(blank=True, null=True)),
                ('max_length', models.PositiveIntegerField(blank=True, null=True)),
                ('min_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('max_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('options', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='forms.form')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('form', 'order')},
            },
        ),
    ]
