# Generated by Django 5.2.7 on 2025-10-02 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('text', 'Text'), ('email', 'Email'), ('number', 'Number'), ('date', 'Date'), ('textarea', 'Textarea'), ('radio', 'Radio'), ('checkbox', 'Checkbox'), ('dropdown', 'Dropdown'), ('multiselect', 'Multi-select')], max_length=50),
        ),
    ]
