# Generated by Django 5.2.7 on 2026-03-03 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0004_add_publish_and_limit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='form',
            name='is_published',
        ),
        migrations.AddField(
            model_name='form',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('CLOSED', 'Closed'), ('EXPIRED', 'Expired')], default='DRAFT', max_length=20),
        ),
        migrations.AddField(
            model_name='form',
            name='success_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
